
// Alle deutschen Feiertage für 2026, 2027, 2028 (von https://www.api-feiertage.de/)
const holidays = [
    {
        "date": "2026-01-01",
        "fname": "Neujahr",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2026-03-27",
        "fname": "Jonas Testfeiertag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2026-04-03",
        "fname": "Karfreitag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2026-04-06",
        "fname": "Ostermontag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2026-05-01",
        "fname": "Tag der Arbeit",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2026-05-14",
        "fname": "Christi Himmelfahrt",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2026-05-25",
        "fname": "Pfingstmontag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2026-10-03",
        "fname": "Tag der deutschen Einheit",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2026-10-31",
        "fname": "Reformationstag",
        "all_states": "0",
        "bw": "0",
        "by": "0",
        "be": "0",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "0",
        "mv": "1",
        "ni": "1",
        "nw": "0",
        "rp": "0",
        "sl": "0",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2026-11-18",
        "fname": "Buß- und Bettag",
        "all_states": "0",
        "bw": "0",
        "by": "0",
        "be": "0",
        "bb": "0",
        "hb": "0",
        "hh": "0",
        "he": "0",
        "mv": "0",
        "ni": "0",
        "nw": "0",
        "rp": "0",
        "sl": "0",
        "sn": "1",
        "st": "0",
        "sh": "0",
        "th": "0",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2026-12-25",
        "fname": "1. Weihnachtstag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2026-12-26",
        "fname": "2. Weihnachtstag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2027-01-01",
        "fname": "Neujahr",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2027-03-26",
        "fname": "Karfreitag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2027-03-29",
        "fname": "Ostermontag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2027-05-01",
        "fname": "Tag der Arbeit",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2027-05-06",
        "fname": "Christi Himmelfahrt",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2027-05-17",
        "fname": "Pfingstmontag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2027-10-03",
        "fname": "Tag der Deutschen Einheit",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2027-10-31",
        "fname": "Reformationstag",
        "all_states": "0",
        "bw": "0",
        "by": "0",
        "be": "0",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "0",
        "mv": "1",
        "ni": "1",
        "nw": "0",
        "rp": "0",
        "sl": "0",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2027-11-17",
        "fname": "Buß- und Bettag",
        "all_states": "0",
        "bw": "0",
        "by": "0",
        "be": "0",
        "bb": "0",
        "hb": "0",
        "hh": "0",
        "he": "0",
        "mv": "0",
        "ni": "0",
        "nw": "0",
        "rp": "0",
        "sl": "0",
        "sn": "1",
        "st": "0",
        "sh": "0",
        "th": "0",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2027-12-25",
        "fname": "1. Weihnachtstag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2027-12-26",
        "fname": "2. Weihnachtstag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-01-01",
        "fname": "Neujahr",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-04-14",
        "fname": "Karfreitag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-04-17",
        "fname": "Ostermontag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-05-01",
        "fname": "Tag der Arbeit",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-05-25",
        "fname": "Christi Himmelfahrt",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-06-05",
        "fname": "Pfingstmontag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-06-15",
        "fname": "Fronleichnam",
        "all_states": "0",
        "bw": "1",
        "by": "1",
        "be": "0",
        "bb": "0",
        "hb": "0",
        "hh": "0",
        "he": "1",
        "mv": "0",
        "ni": "0",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "0",
        "sh": "0",
        "th": "1",
        "comment": "Fronleichnam ist in Sachsen nur in den vom Staatsministerium des Inneren bestimmten Regionen ein gesetzlicher Feiertag. Fronleichnam ist in Thüringen nur in Gemeinden mit überwiegend katholischer Bevölkerung ein gesetzlicher Feiertag",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-10-03",
        "fname": "Tag der Deutschen Einheit",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-10-31",
        "fname": "Reformationstag",
        "all_states": "0",
        "bw": "0",
        "by": "0",
        "be": "0",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "0",
        "mv": "1",
        "ni": "1",
        "nw": "0",
        "rp": "0",
        "sl": "0",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-11-22",
        "fname": "Buß- und Bettag",
        "all_states": "0",
        "bw": "0",
        "by": "0",
        "be": "0",
        "bb": "0",
        "hb": "0",
        "hh": "0",
        "he": "0",
        "mv": "0",
        "ni": "0",
        "nw": "0",
        "rp": "0",
        "sl": "0",
        "sn": "1",
        "st": "0",
        "sh": "0",
        "th": "0",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-12-25",
        "fname": "1. Weihnachtstag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    },
    {
        "date": "2028-12-26",
        "fname": "2. Weihnachtstag",
        "all_states": "1",
        "bw": "1",
        "by": "1",
        "be": "1",
        "bb": "1",
        "hb": "1",
        "hh": "1",
        "he": "1",
        "mv": "1",
        "ni": "1",
        "nw": "1",
        "rp": "1",
        "sl": "1",
        "sn": "1",
        "st": "1",
        "sh": "1",
        "th": "1",
        "comment": "",
        "augsburg": null,
        "katholisch": null
    }
];

// Sucht nur Feiertage des aktuellen Monats
function filterCurrentHolidays() {
    let currentHolidays = [];
    let now = new Date();
    holidays.forEach((holiday) => {
        let holidayDate = new Date(holiday.date);
        if (holidayDate.getFullYear() === now.getFullYear() && holidayDate.getMonth() === now.getMonth()) {
            currentHolidays.push(holiday);
        }
    })
    return currentHolidays;
}

let currentHolidays = filterCurrentHolidays();

// Erstelle einen Listeneintrag für jeden Feiertag diesen Monat
const holidayCard = document.getElementById("holiday-card");

if (currentHolidays.length !== 0) {
    currentHolidays.forEach((holiday) => {
        let item = document.createElement("p");
        item.classList.add('holiday__item');
        holidayCard.appendChild(item);
        
        let dateString = document.createElement("span");
        dateString.classList.add('holiday__date');
        dateString.innerText = holiday.date;

        let nameString = document.createElement("span");
        nameString.innerText = " - " + holiday.fname;
        item.appendChild(dateString);
        item.appendChild(nameString);
    })
} else {
    let placeholder = document.createElement("p");
    placeholder.innerText = "Diesen Monat gibt es keine Feiertage.";
    holidayCard.appendChild(placeholder);
}


